version: '3.9'

networks:
  default:
    name: "Default Switch"
    external: true

services:
  win-action1:
    build:
      context: .
      dockerfile: Dockerfile
    # entrypoint: ["pwsh", "-Command", "Start-Sleep", "-Seconds", "2147483"]
    env_file:
      - .env

  # win-test:
  #   image: mcr.microsoft.com/windows/servercore:1809
  #   entrypoint: ["powershell", "-Command", "Start-Sleep", "-Seconds", "2147483"]

