name: test-windows
on:
  # push, pullrequest時にci実行
  push:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - '**.md'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - '**.md'

jobs:
  build:
    name: test-windows
    runs-on: ['Windows', 'self-hosted', 'X64']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: test-windows
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path "C:\actions-runner"
          New-Item -ItemType File -Path "C:\actions-runner\myfile.txt"
          Get-Content -Path "C:\actions-runner\myfile.txt"
          Get-Location
